language: shell
os:
  - linux
  - osx
sudo: required
dist: trusty


# Note: needed by winetricks-test, which not yet supported in TravisCI
# - cabextract
# - p7zip
# - unrar
# - unzip
# - wine

addons:
  apt:
    packages:
    # for checkbashisms
    - devscripts

# Note: if statements cannot go across multiple lines. Combine into one, or move to a shell script!

# On Ubuntu, shellcheck is not in trusty, but is in trusty-backports, but those aren't available in TravisCI..)
# Using zesty to get 0.4.4, which has support for disabling a check globally within a file
# Also, modern Wine is only on yakkety/zesty

# Stable wine for both?
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then echo 'adding repositories' ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then echo "deb http://archive.ubuntu.com/ubuntu/ zesty universe" | sudo tee -a /etc/apt/sources.list ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then time sudo apt-get -q update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then time sudo dpkg --add-architecture i386 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then echo 'install dependencies' ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then time sudo apt-get install shellcheck wine-stable ; fi

# Would like --devel wine, but that compiles from source, which takes longer than Travis CI runs for
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then time brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then time brew install checkbashisms shellcheck ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then time brew install wine ; fi

script: time sh ./tests/shell-checks
