language: shell
os:
  - linux
  - osx
sudo: required
dist: trusty


# Note: needed by winetricks-test, which not yet supported in TravisCI
# - cabextract
# - p7zip
# - unrar
# - unzip
# - wine

addons:
  apt:
    packages:
    # for checkbashisms
    - devscripts
    - wine

# Note: if statements cannot go across multiple lines. Combine into one, or move to a shell script!

# On Ubuntu, shellcheck is not in trusty, but is in trusty-backports, but those aren't available in TravisCI..)
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then echo "deb http://archive.ubuntu.com/ubuntu/ xenial universe" | sudo tee -a /etc/apt/sources.list ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then time sudo apt-get -q update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then time sudo apt-get install shellcheck ; fi

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then time brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then time brew install checkbashisms shellcheck ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then time brew install --devel wine ; fi

#script: time sh ./tests/shell-checks

script: time sh ./src/winetricks -q -v dotnet40
